#ifndef NOGGIT_CONTEXTOBJECT_HPP
#define NOGGIT_CONTEXTOBJECT_HPP

namespace Noggit
{
  enum NoggitRenderContext
  {
    MAP_VIEW,
    ASSET_BROWSER,
    ASSET_BROWSER_PREVIEW,
    OBJECT_PALETTE_PREVIEW,
    PRESET_EDITOR,
    PRESET_EDITOR_PREVIEW,
    GROUND_EFFECT_PREVIEW,
    BLP_RENDERER,
    count
  };
}

#endif //NOGGIT_CONTEXTOBJECT_HPP
