#ifndef NOGGIT_CONTEXTOBJECT_HPP
#define NOGGIT_CONTEXTOBJECT_HPP

namespace noggit
{
  enum NoggitRenderContext
  {
    MAP_VIEW,
    ASSET_BROWSER,
    ASSET_BROWSER_PREVIEW,
    OBJECT_PALETTE_PREVIEW,
    PRESET_EDITOR,
    PRESET_EDITOR_PREVIEW,
    BLP_RENDERER
  };
}

#endif //NOGGIT_CONTEXTOBJECT_HPP
